//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FestManager_Core.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FestManager_Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Laden der Daten:  ähnelt.
        /// </summary>
        internal static string Database_Error_Message_Pfx {
            get {
                return ResourceManager.GetString("Database_Error_Message_Pfx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datenbankfehler ähnelt.
        /// </summary>
        internal static string Database_Error_Message_Title {
            get {
                return ResourceManager.GetString("Database_Error_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Verbinden mit der Datenbank! Wollen Sie den Speicherort der Datenbank prüfen? ähnelt.
        /// </summary>
        internal static string Error_connection_to_DB_Msg {
            get {
                return ResourceManager.GetString("Error_connection_to_DB_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datenbank-Verbindungsfehler ähnelt.
        /// </summary>
        internal static string Error_connection_to_DB_Title {
            get {
                return ResourceManager.GetString("Error_connection_to_DB_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler ähnelt.
        /// </summary>
        internal static string FormBestellung_abschliessenButton_Click_Error {
            get {
                return ResourceManager.GetString("FormBestellung_abschliessenButton_Click_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Speichern der Bestellung! ähnelt.
        /// </summary>
        internal static string FormBestellung_abschliessenButton_Click_Error_saving_order {
            get {
                return ResourceManager.GetString("FormBestellung_abschliessenButton_Click_Error_saving_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ungültiger Kellner gewählt! ähnelt.
        /// </summary>
        internal static string FormBestellung_abschliessenButton_Click_Invalid_Waiter_selected {
            get {
                return ResourceManager.GetString("FormBestellung_abschliessenButton_Click_Invalid_Waiter_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bestellung abgeschlossen!
        ///Gesamtpreis in €:  ähnelt.
        /// </summary>
        internal static string FormBestellung_abschliessenButton_Click_Order_placed {
            get {
                return ResourceManager.GetString("FormBestellung_abschliessenButton_Click_Order_placed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der angegebene Artikel konnte nicht gefunden werden! ähnelt.
        /// </summary>
        internal static string FormBestellung_artikelDataGridView_CellValidated_Product_not_found {
            get {
                return ResourceManager.GetString("FormBestellung_artikelDataGridView_CellValidated_Product_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Artikel nicht gefunden ähnelt.
        /// </summary>
        internal static string FormBestellung_artikelDataGridView_CellValidated_Product_not_found_Title {
            get {
                return ResourceManager.GetString("FormBestellung_artikelDataGridView_CellValidated_Product_not_found_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler: Kein &apos;Kassa&apos;-Drucker eingerichtet !! ähnelt.
        /// </summary>
        internal static string FormBestellung_PrintBestellung_Error_no_POS_printer_configured {
            get {
                return ResourceManager.GetString("FormBestellung_PrintBestellung_Error_no_POS_printer_configured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler: Bestellung wird nicht gedruckt! Bitte starten Sie die Applikation neu. ähnelt.
        /// </summary>
        internal static string FormBestellung_PrintKassabon_Critical_error_restart_application {
            get {
                return ResourceManager.GetString("FormBestellung_PrintKassabon_Critical_error_restart_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Drucken ähnelt.
        /// </summary>
        internal static string FormBestellung_PrintKassabon_Printing_error {
            get {
                return ResourceManager.GetString("FormBestellung_PrintKassabon_Printing_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bestellung wird nun storniert... ähnelt.
        /// </summary>
        internal static string FormBestellung_stornierenButton_Click_Order_will_be_canceled {
            get {
                return ResourceManager.GetString("FormBestellung_stornierenButton_Click_Order_will_be_canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bestell-Details für # ähnelt.
        /// </summary>
        internal static string FormBestellungenHistory_bestellungenHistoryDataGridView_CellDoubleClick_Order_details_for {
            get {
                return ResourceManager.GetString("FormBestellungenHistory_bestellungenHistoryDataGridView_CellDoubleClick_Order_det" +
                        "ails_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler: Kein &apos;Kassa&apos;-Drucker eingerichtet !! ähnelt.
        /// </summary>
        internal static string FormBestellungenHistory_buttonPrintBestellung_Click_Error_no_POS_printer {
            get {
                return ResourceManager.GetString("FormBestellungenHistory_buttonPrintBestellung_Click_Error_no_POS_printer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Drucken ähnelt.
        /// </summary>
        internal static string FormBestellungenHistory_buttonPrintBestellung_Click_Printing_error {
            get {
                return ResourceManager.GetString("FormBestellungenHistory_buttonPrintBestellung_Click_Printing_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alle offenen Abrechnungen werden als &apos;abgerechnet&apos; markiert. Fortfahren? ähnelt.
        /// </summary>
        internal static string FormKellnerabrechnung_buttonCloseOrders_Click_Continue_on_mark_all_open_orders_finalized {
            get {
                return ResourceManager.GetString("FormKellnerabrechnung_buttonCloseOrders_Click_Continue_on_mark_all_open_orders_fi" +
                        "nalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abrechnungen dauerhaft abschließen ähnelt.
        /// </summary>
        internal static string FormKellnerabrechnung_buttonCloseOrders_Click_Finalize_orders {
            get {
                return ResourceManager.GetString("FormKellnerabrechnung_buttonCloseOrders_Click_Finalize_orders", resourceCulture);
            }
        }
    }
}
